name: 🐞 Issue report
description: Report an issue
labels: [Bug]
body:

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: crash-logs
    attributes:
      label: Crash logs
      description: |
        If you have crash logs please add them here.
      placeholder: |
        You can paste the crash logs in plain text or upload it as an attachment.

  - type: input
    id: app-version
    attributes:
      label: App version
      description: Add the app version here.
      placeholder: |
        Example: "0.0.6"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device, model and version.
      placeholder: |
        Example: "Google Pixel 5 - Android 12"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to version.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
